apiVersion: v1
kind: Secret
metadata:
  name: db-password
  namespace: pih-app
type: Opaque
data:
  db-password: ZGItNTd4c2w=
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: pih-app
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: pih-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: pihpoldevcrdocker2r6l.azurecr.io/react-java-mysql-backend:latest
          imagePullPolicy: Always
          env:
            - name: MYSQL_HOST
              value: db
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: db-password
              mountPath: /run/secrets/db-password
              subPath: db-password
              readOnly: true
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/readiness
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/liveness
            initialDelaySeconds: 60
            periodSeconds: 1
      volumes:
        - name: db-password
          secret:
            secretName: db-password
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: pih-app
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  namespace: pih-app
spec:
  replicas: 1
  serviceName: db
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: mariadb:10.6.4-focal
          env:
            - name: MYSQL_DATABASE
              value: example
            - name: MYSQL_ROOT_PASSWORD_FILE
              value: /run/secrets/db-password
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/mysql
            - name: db-password
              mountPath: /run/secrets/db-password
              subPath: db-password
              readOnly: true
          livenessProbe:
            exec:
              command: ["mysqladmin", "ping"]
            initialDelaySeconds: 30
            periodSeconds: 3
            failureThreshold: 5
      volumes:
        - name: db-data
          emptyDir: {}
        - name: db-password
          secret:
            secretName: db-password
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  namespace: pih-app
spec:
  selector:
    app: phpmyadmin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  namespace: pih-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin/phpmyadmin:latest
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: db
            - name: PMA_ABSOLUTE_URI
              value: http://20.215.98.9/phpmyadmin/
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: pih-app
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: pih-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: pihpoldevcrdocker2r6l.azurecr.io/react-java-mysql-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pih-app-ingress
  namespace: pih-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  rules:
    - http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: frontend
                port:
                  number: 80
          - path: /api
            pathType: ImplementationSpecific
            backend:
              service:
                name: backend
                port:
                  number: 80
          - path: /phpmyadmin
            pathType: ImplementationSpecific
            backend:
              service:
                name: phpmyadmin
                port:
                  number: 80
