apiVersion: v1
kind: Secret
metadata:
  name: db-password
  namespace: pih-app
type: Opaque
data:
  db-password: ZGItNTd4c2w=
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: pih-app
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: pih-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: pihpoldevcrdockerxhub.azurecr.io/react-java-mysql-backend:latest
          imagePullPolicy: Always
          env:
            - name: MYSQL_HOST
              value: db
          ports:
            - containerPort: 80
          volumeMounts:
            - name: db-password
              mountPath: /run/secrets/db-password
              subPath: db-password
              readOnly: true
          readinessProbe:
            httpGet:
              port: healthcheck
              path: /actuator/health/readiness
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              port: healthcheck
              path: /actuator/health/liveness
            initialDelaySeconds: 60
            periodSeconds: 1
      volumes:
        - name: db-password
          secret:
            secretName: db-password
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: pih-app
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  namespace: pih-app
spec:
  replicas: 1
  serviceName: db
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: mariadb:10.6.4-focal
          env:
            - name: MYSQL_DATABASE
              value: example
            - name: MYSQL_ROOT_PASSWORD_FILE
              value: /run/secrets/db-password
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/mysql
            - name: db-password
              mountPath: /run/secrets/db-password
              subPath: db-password
              readOnly: true
          livenessProbe:
            exec:
              command: ["mysqladmin", "ping"]
            initialDelaySeconds: 30
            periodSeconds: 3
            failureThreshold: 5
      volumes:
        - name: db-data
          emptyDir: {}
        - name: db-password
          secret:
            secretName: db-password
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  namespace: pih-app
spec:
  selector:
    app: phpmyadmin
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  namespace: pih-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin/phpmyadmin:latest
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: db
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: pih-app
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: pih-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: pihpoldevcrdockerxhub.azurecr.io/react-java-mysql-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5